import { useCallback, useEffect, useState } from "react";
import { FaArrowLeft, FaCheckCircle, FaReceipt, FaSearch, FaShieldAlt, FaTimesCircle } from "react-icons/fa";
import { Link, useNavigate, useParams } from "react-router-dom";
import { API_URL } from "../lib/api";
import "../styles/receipt-verification.css";

const CODE_PATTERN = /^[0-9a-f]{32}$/i;
const formatDate = (value) => new Intl.DateTimeFormat("en-PH", { dateStyle: "long", timeStyle: "short" }).format(new Date(value));

export default function VerifyReceipt() {
  const { code: routeCode = "" } = useParams();
  const navigate = useNavigate();
  const [input, setInput] = useState(routeCode);
  const [state, setState] = useState({ status: routeCode ? "loading" : "idle", receipt: null, message: "" });

  const verify = useCallback(async (candidate) => {
    const code = String(candidate || "").trim().toLowerCase();
    if (!CODE_PATTERN.test(code)) {
      setState({ status: "invalid", receipt: null, message: "Enter the complete 32-character verification code." });
      return;
    }
    setState({ status: "loading", receipt: null, message: "" });
    try {
      const response = await fetch(`${API_URL}/api/receipts/verify/${encodeURIComponent(code)}`);
      const body = await response.json();
      if (!response.ok || !body.valid) {
        setState({ status: "invalid", receipt: null, message: body.message || "This receipt could not be verified." });
        return;
      }
      setState({ status: "verified", receipt: body.receipt, message: "" });
    } catch {
      setState({ status: "error", receipt: null, message: "The verification service could not be reached. Check your connection and try again." });
    }
  }, []);

  useEffect(() => {
    if (!routeCode) return undefined;
    const timer = window.setTimeout(() => verify(routeCode), 0);
    return () => window.clearTimeout(timer);
  }, [routeCode, verify]);

  function submit(event) {
    event.preventDefault();
    const code = input.trim().toLowerCase();
    if (CODE_PATTERN.test(code) && code !== routeCode.toLowerCase()) navigate(`/verify-receipt/${code}`);
    else verify(code);
  }

  return <main className="verify-receipt-page">
    <section className="verify-receipt-card">
      <div className="verify-brand"><span><FaShieldAlt /> CTHM Stockroom</span><Link to="/login"><FaArrowLeft /> Sign in</Link></div>
      <div className="verify-heading"><div><FaReceipt /></div><h1>Verify a receipt</h1><p>Confirm that a borrowing claim or return receipt was generated by the CTHM Stockroom System.</p></div>
      <form onSubmit={submit}><label htmlFor="receipt-code">Receipt verification code</label><div><input id="receipt-code" value={input} onChange={(event) => setInput(event.target.value)} placeholder="Enter the 32-character code" maxLength={32} autoComplete="off" spellCheck="false" /><button disabled={state.status === "loading"}><FaSearch /> {state.status === "loading" ? "Checking…" : "Verify"}</button></div></form>
      {state.status === "idle" && <div className="verify-guidance"><FaShieldAlt /><p>The code is printed below the QR on an official receipt. Scanning its QR opens this page automatically.</p></div>}
      {state.status === "loading" && <div className="verify-loading" role="status"><span /><p>Checking the official receipt registry…</p></div>}
      {state.status === "verified" && <article className="verification-result verified"><FaCheckCircle /><div><span>Authentic system receipt</span><h2>{state.receipt.receipt_number}</h2><dl><div><dt>Transaction</dt><dd>{state.receipt.receipt_type === "claim" ? "Item claim" : "Item return"}</dd></div><div><dt>Request reference</dt><dd>BR-{String(state.receipt.request_id).padStart(3, "0")}</dd></div><div><dt>Recorded</dt><dd>{formatDate(state.receipt.created_at)}</dd></div></dl><p>This record exists in the official immutable receipt registry.</p></div></article>}
      {(state.status === "invalid" || state.status === "error") && <article className={`verification-result ${state.status}`} role="alert"><FaTimesCircle /><div><span>{state.status === "invalid" ? "Receipt not verified" : "Verification unavailable"}</span><h2>{state.status === "invalid" ? "No authentic record found" : "Please try again"}</h2><p>{state.message}</p><button type="button" onClick={() => verify(input)}>Try Again</button></div></article>}
      <footer>Verification intentionally excludes borrower names, student IDs, and item details to protect personal information.</footer>
    </section>
  </main>;
}
