"use strict";
const express = require("express");
const { authenticate } = require("../middleware/auth");
const { listNotifications, markAllNotificationsRead, markNotificationRead } = require("../controllers/notificationController");
const router = express.Router();
router.use(authenticate);
router.get("/", listNotifications);
router.patch("/read-all", markAllNotificationsRead);
router.patch("/:id/read", markNotificationRead);
module.exports = router;
