"use strict";
const express = require("express");
const { authenticate, requireRoles } = require("../middleware/auth");
const { closeScannerPairing, createScannerPairing, getManagedUserQr, getMyQr, getPairingResult, issueManagedUserQr, joinScannerPairing, lookupReadyRequest, recordManagedUserQrPrint, replaceManagedUserQr, revokeManagedUserQr, submitPairedScan } = require("../controllers/qrController");
const { lookupAssetQr } = require("../controllers/assetController");
const router = express.Router();
router.use(authenticate);
router.get("/me", getMyQr);
router.get("/users/:id", requireRoles("admin"), getManagedUserQr);
router.post("/users/:id/issue", requireRoles("admin"), issueManagedUserQr);
router.post("/users/:id/revoke", requireRoles("admin"), revokeManagedUserQr);
router.post("/users/:id/replace", requireRoles("admin"), replaceManagedUserQr);
router.post("/users/:id/print", requireRoles("admin"), recordManagedUserQrPrint);
router.post("/lookup", requireRoles("staff", "admin"), lookupReadyRequest);
router.post("/assets/lookup", requireRoles("staff", "admin"), lookupAssetQr);
router.post("/pairings", requireRoles("staff", "admin"), createScannerPairing);
router.post("/pairings/join", requireRoles("staff", "admin"), joinScannerPairing);
router.post("/pairings/scan", requireRoles("staff", "admin"), submitPairedScan);
router.get("/pairings/:id", requireRoles("staff", "admin"), getPairingResult);
router.delete("/pairings/:id", requireRoles("staff", "admin"), closeScannerPairing);
module.exports = router;
