begin;

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  actor_email text,
  actor_name text,
  actor_role text,
  action text not null check (action ~ '^[a-z0-9_]+$'),
  entity_type text not null check (entity_type ~ '^[a-z0-9_]+$'),
  entity_id text,
  old_values jsonb,
  new_values jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_created_at_idx on public.audit_logs (created_at desc, id desc);
create index if not exists audit_logs_entity_idx on public.audit_logs (entity_type, entity_id);
create index if not exists audit_logs_actor_idx on public.audit_logs (actor_user_id, created_at desc);

alter table public.audit_logs enable row level security;
revoke all on public.audit_logs from anon, authenticated;
grant select on public.audit_logs to authenticated;

drop policy if exists audit_logs_admin_read on public.audit_logs;
create policy audit_logs_admin_read on public.audit_logs for select to authenticated
using (public.current_user_role() = 'admin');

create or replace function public.audit_inventory_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  profile_row public.profiles%rowtype;
  actor_id uuid := auth.uid();
begin
  -- API writes are logged by the API in the same transaction. This trigger
  -- captures authenticated browser writes made directly through Supabase.
  if actor_id is null then
    if tg_op = 'DELETE' then return old; end if;
    return new;
  end if;

  select * into profile_row from public.profiles where user_id = actor_id;
  insert into public.audit_logs (
    actor_user_id, actor_name, actor_role, action, entity_type, entity_id,
    old_values, new_values
  ) values (
    actor_id, profile_row.full_name, profile_row.role,
    case tg_op when 'INSERT' then 'inventory_created'
      when 'UPDATE' then 'inventory_updated' else 'inventory_deleted' end,
    'inventory', coalesce(new.id, old.id)::text,
    case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end
  );
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

drop trigger if exists inventory_audit_trigger on public.inventory;
create trigger inventory_audit_trigger
after insert or update or delete on public.inventory
for each row execute function public.audit_inventory_change();

revoke all on function public.audit_inventory_change() from public;

commit;
