begin;

alter table public.inventory
  add column if not exists tracking_type text not null default 'bulk';

alter table public.inventory drop constraint if exists inventory_tracking_type_check;
alter table public.inventory add constraint inventory_tracking_type_check
  check (tracking_type in ('bulk', 'serialized'));

create table if not exists public.inventory_assets (
  id bigint generated by default as identity primary key,
  inventory_id bigint not null references public.inventory(id) on delete restrict,
  asset_number text not null unique,
  serial_number text,
  qr_public_id uuid not null default gen_random_uuid() unique,
  qr_version integer not null default 1 check (qr_version > 0),
  condition text not null default 'good'
    check (condition in ('good', 'fair', 'damaged', 'under_inspection', 'retired')),
  status text not null default 'available'
    check (status in ('available', 'borrowed', 'maintenance', 'retired')),
  current_borrow_request_id bigint references public.borrow_requests(id) on delete restrict,
  current_borrower_user_id uuid references auth.users(id) on delete set null,
  last_inspected_at timestamptz,
  last_inspected_by uuid references auth.users(id) on delete set null,
  maintenance_note text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint inventory_assets_serial_number_length check (serial_number is null or char_length(serial_number) between 1 and 120),
  constraint inventory_assets_maintenance_note_length check (maintenance_note is null or char_length(maintenance_note) <= 1000),
  constraint inventory_assets_assignment_state check (
    (status = 'borrowed' and current_borrow_request_id is not null and current_borrower_user_id is not null)
    or (status <> 'borrowed' and current_borrow_request_id is null and current_borrower_user_id is null)
  ),
  constraint inventory_assets_operational_state check (
    (status = 'available' and condition in ('good', 'fair'))
    or (status = 'borrowed' and condition in ('good', 'fair'))
    or (status = 'maintenance' and condition in ('damaged', 'under_inspection'))
    or (status = 'retired' and condition = 'retired')
  )
);

create unique index if not exists inventory_assets_serial_number_unique
  on public.inventory_assets(lower(serial_number)) where serial_number is not null;
create index if not exists inventory_assets_inventory_status_idx
  on public.inventory_assets(inventory_id, status);

create table if not exists public.borrowing_asset_assignments (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.borrow_requests(id) on delete restrict,
  inventory_id bigint not null references public.inventory(id) on delete restrict,
  asset_id bigint not null references public.inventory_assets(id) on delete restrict,
  released_by uuid references auth.users(id) on delete set null,
  released_at timestamptz not null default now(),
  returned_by uuid references auth.users(id) on delete set null,
  returned_at timestamptz,
  return_condition text check (return_condition is null or return_condition in ('good', 'fair', 'damaged', 'missing')),
  condition_note text check (condition_note is null or char_length(condition_note) <= 500),
  unique(request_id, asset_id),
  constraint borrowing_asset_return_state check (
    (returned_at is null and returned_by is null and return_condition is null)
    or (returned_at is not null and returned_by is not null and return_condition is not null)
  )
);

create unique index if not exists borrowing_asset_one_active_assignment
  on public.borrowing_asset_assignments(asset_id) where returned_at is null;
create index if not exists borrowing_asset_request_idx
  on public.borrowing_asset_assignments(request_id, inventory_id);

alter table public.inventory_assets enable row level security;
alter table public.borrowing_asset_assignments enable row level security;
drop policy if exists inventory_assets_authenticated_read on public.inventory_assets;
create policy inventory_assets_authenticated_read on public.inventory_assets
  for select to authenticated using (true);
drop policy if exists borrowing_assets_own_or_staff_read on public.borrowing_asset_assignments;
create policy borrowing_assets_own_or_staff_read on public.borrowing_asset_assignments
  for select to authenticated using (
    exists (select 1 from public.profiles p where p.user_id = auth.uid() and p.role in ('admin', 'professor'))
    or exists (select 1 from public.borrow_requests r where r.id = request_id and r.user_id = auth.uid())
  );

revoke insert, update, delete on public.inventory_assets from anon, authenticated;
revoke insert, update, delete on public.borrowing_asset_assignments from anon, authenticated;
grant select on public.inventory_assets, public.borrowing_asset_assignments to authenticated;

do $$ begin
  alter publication supabase_realtime add table public.inventory_assets;
exception when duplicate_object then null;
end $$;

commit;
