begin;

alter table public.inventory_assets drop constraint if exists inventory_assets_condition_check;
alter table public.inventory_assets add constraint inventory_assets_condition_check
  check (condition in ('good', 'fair', 'damaged', 'under_inspection', 'missing', 'retired'));
alter table public.inventory_assets drop constraint if exists inventory_assets_status_check;
alter table public.inventory_assets add constraint inventory_assets_status_check
  check (status in ('available', 'borrowed', 'maintenance', 'missing', 'retired'));
alter table public.inventory_assets drop constraint if exists inventory_assets_operational_state;
alter table public.inventory_assets add constraint inventory_assets_operational_state check (
  (status = 'available' and condition in ('good', 'fair'))
  or (status = 'borrowed' and condition in ('good', 'fair'))
  or (status = 'maintenance' and condition in ('damaged', 'under_inspection'))
  or (status = 'missing' and condition = 'missing')
  or (status = 'retired' and condition = 'retired')
);

create table if not exists public.serialized_asset_incidents (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.borrow_requests(id) on delete restrict,
  assignment_id bigint not null unique references public.borrowing_asset_assignments(id) on delete restrict,
  asset_id bigint not null references public.inventory_assets(id) on delete restrict,
  incident_type text not null default 'missing' check (incident_type = 'missing'),
  reason text not null check (char_length(btrim(reason)) between 5 and 500),
  status text not null default 'open' check (status in ('open', 'recovered', 'written_off')),
  reported_by uuid references auth.users(id) on delete set null,
  reported_at timestamptz not null default now(),
  resolved_by uuid references auth.users(id) on delete set null,
  resolved_at timestamptz,
  resolution_note text check (resolution_note is null or char_length(resolution_note) <= 500),
  constraint serialized_incident_resolution_state check (
    (status = 'open' and resolved_by is null and resolved_at is null)
    or (status <> 'open' and resolved_by is not null and resolved_at is not null)
  )
);
create index if not exists serialized_asset_incidents_status_idx
  on public.serialized_asset_incidents(status, reported_at desc);

alter table public.serialized_asset_incidents enable row level security;
drop policy if exists serialized_incidents_staff_read on public.serialized_asset_incidents;
create policy serialized_incidents_staff_read on public.serialized_asset_incidents for select to authenticated using (
  exists (select 1 from public.profiles p where p.user_id=auth.uid() and p.role in ('admin','professor'))
);
revoke insert, update, delete on public.serialized_asset_incidents from anon, authenticated;
grant select on public.serialized_asset_incidents to authenticated;

commit;
