begin;

create table if not exists public.inventory_reconciliations (
  id uuid primary key default gen_random_uuid(),
  status text not null default 'in_progress' check (status in ('in_progress','completed','cancelled')),
  notes text check (notes is null or char_length(notes) <= 1000),
  adjustment_reason text check (adjustment_reason is null or char_length(adjustment_reason) <= 1000),
  started_by uuid references auth.users(id) on delete set null,
  started_at timestamptz not null default now(),
  completed_by uuid references auth.users(id) on delete set null,
  completed_at timestamptz,
  apply_adjustments boolean not null default false,
  constraint inventory_reconciliation_completion check (
    (status = 'in_progress' and completed_by is null and completed_at is null)
    or (status <> 'in_progress' and completed_at is not null)
  )
);

create unique index if not exists one_active_inventory_reconciliation
  on public.inventory_reconciliations((status)) where status='in_progress';

create table if not exists public.inventory_reconciliation_items (
  id bigint generated by default as identity primary key,
  reconciliation_id uuid not null references public.inventory_reconciliations(id) on delete restrict,
  inventory_id bigint not null references public.inventory(id) on delete restrict,
  tracking_type text not null check (tracking_type in ('bulk','serialized')),
  expected_on_hand integer not null check (expected_on_hand >= 0),
  counted_on_hand integer check (counted_on_hand is null or counted_on_hand >= 0),
  discrepancy integer,
  unique(reconciliation_id, inventory_id)
);

create table if not exists public.inventory_reconciliation_assets (
  id bigint generated by default as identity primary key,
  reconciliation_id uuid not null references public.inventory_reconciliations(id) on delete restrict,
  asset_id bigint not null references public.inventory_assets(id) on delete restrict,
  inventory_id bigint not null references public.inventory(id) on delete restrict,
  expected_status text not null,
  expected_condition text not null,
  observed_condition text check (observed_condition is null or observed_condition in ('good','fair','damaged','under_inspection')),
  scanned_at timestamptz,
  scanned_by uuid references auth.users(id) on delete set null,
  discrepancy_type text check (discrepancy_type is null or discrepancy_type in ('not_found','unexpected','condition_mismatch')),
  unique(reconciliation_id, asset_id)
);

alter table public.inventory_reconciliations enable row level security;
alter table public.inventory_reconciliation_items enable row level security;
alter table public.inventory_reconciliation_assets enable row level security;
drop policy if exists reconciliation_admin_read on public.inventory_reconciliations;
create policy reconciliation_admin_read on public.inventory_reconciliations for select to authenticated using (
  exists (select 1 from public.profiles p where p.user_id=auth.uid() and p.role='admin'));
drop policy if exists reconciliation_items_admin_read on public.inventory_reconciliation_items;
create policy reconciliation_items_admin_read on public.inventory_reconciliation_items for select to authenticated using (
  exists (select 1 from public.profiles p where p.user_id=auth.uid() and p.role='admin'));
drop policy if exists reconciliation_assets_admin_read on public.inventory_reconciliation_assets;
create policy reconciliation_assets_admin_read on public.inventory_reconciliation_assets for select to authenticated using (
  exists (select 1 from public.profiles p where p.user_id=auth.uid() and p.role='admin'));
revoke insert, update, delete on public.inventory_reconciliations, public.inventory_reconciliation_items, public.inventory_reconciliation_assets from anon, authenticated;
grant select on public.inventory_reconciliations, public.inventory_reconciliation_items, public.inventory_reconciliation_assets to authenticated;

commit;
