begin;

create table if not exists public.asset_maintenance_records (
  id bigint generated by default as identity primary key,
  asset_id bigint not null references public.inventory_assets(id) on delete restrict,
  inventory_id bigint not null references public.inventory(id) on delete restrict,
  source text not null default 'manual' check (source in ('manual','damaged_return','reconciliation')),
  status text not null default 'under_inspection'
    check (status in ('under_inspection','under_repair','completed','retired')),
  problem_description text not null check (char_length(trim(problem_description)) between 5 and 1000),
  repair_notes text check (repair_notes is null or char_length(repair_notes) <= 2000),
  assigned_to uuid references auth.users(id) on delete set null,
  due_date date,
  cost numeric(12,2) not null default 0 check (cost >= 0),
  opened_by uuid references auth.users(id) on delete set null,
  opened_at timestamptz not null default now(),
  completed_by uuid references auth.users(id) on delete set null,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint asset_maintenance_completion check (
    (status in ('under_inspection','under_repair') and completed_at is null and completed_by is null)
    or (status in ('completed','retired') and completed_at is not null)
  )
);

create unique index if not exists one_open_maintenance_per_asset
  on public.asset_maintenance_records(asset_id)
  where status in ('under_inspection','under_repair');
create index if not exists asset_maintenance_inventory_idx
  on public.asset_maintenance_records(inventory_id, opened_at desc);
create index if not exists asset_maintenance_due_idx
  on public.asset_maintenance_records(due_date)
  where status in ('under_inspection','under_repair');

insert into public.asset_maintenance_records
  (asset_id, inventory_id, source, status, problem_description, assigned_to, opened_by, opened_at)
select asset.id, asset.inventory_id, 'manual', 'under_inspection',
       case when char_length(trim(coalesce(asset.maintenance_note,''))) >= 5
            then trim(asset.maintenance_note) else 'Existing maintenance case migrated from asset status.' end,
       asset.last_inspected_by, asset.last_inspected_by, coalesce(asset.updated_at, now())
  from public.inventory_assets asset
 where asset.status='maintenance'
   and not exists (
     select 1 from public.asset_maintenance_records record
      where record.asset_id=asset.id and record.status in ('under_inspection','under_repair')
   );

alter table public.asset_maintenance_records enable row level security;
drop policy if exists asset_maintenance_admin_read on public.asset_maintenance_records;
create policy asset_maintenance_admin_read on public.asset_maintenance_records
  for select to authenticated using (
    exists (select 1 from public.profiles profile where profile.user_id=auth.uid() and profile.role='admin')
  );
revoke insert, update, delete on public.asset_maintenance_records from anon, authenticated;
grant select on public.asset_maintenance_records to authenticated;

do $$ begin
  alter publication supabase_realtime add table public.asset_maintenance_records;
exception when duplicate_object then null;
end $$;

commit;
