begin;

alter table public.inventory_assets
  add column if not exists inspection_interval_days integer,
  add column if not exists next_inspection_date date;

alter table public.inventory_assets drop constraint if exists inventory_assets_inspection_interval_check;
alter table public.inventory_assets add constraint inventory_assets_inspection_interval_check
  check (inspection_interval_days is null or inspection_interval_days between 1 and 3650);
alter table public.inventory_assets add constraint inventory_assets_inspection_schedule_check
  check ((inspection_interval_days is null and next_inspection_date is null) or inspection_interval_days is not null);

create index if not exists inventory_assets_inspection_due_idx
  on public.inventory_assets(next_inspection_date)
  where status='available' and next_inspection_date is not null;

create table if not exists public.asset_inspections (
  id bigint generated by default as identity primary key,
  asset_id bigint not null references public.inventory_assets(id) on delete restrict,
  inventory_id bigint not null references public.inventory(id) on delete restrict,
  result text not null check (result in ('good','fair','damaged')),
  notes text not null check (char_length(trim(notes)) between 5 and 1000),
  inspected_by uuid references auth.users(id) on delete set null,
  inspected_at timestamptz not null default now(),
  next_inspection_date date
);

create index if not exists asset_inspections_asset_idx on public.asset_inspections(asset_id, inspected_at desc);
alter table public.asset_inspections enable row level security;
drop policy if exists asset_inspections_admin_read on public.asset_inspections;
create policy asset_inspections_admin_read on public.asset_inspections for select to authenticated using (
  exists (select 1 from public.profiles profile where profile.user_id=auth.uid() and profile.role='admin'));
revoke insert, update, delete on public.asset_inspections from anon, authenticated;
grant select on public.asset_inspections to authenticated;

do $$ begin
  alter publication supabase_realtime add table public.asset_inspections;
exception when duplicate_object then null;
end $$;

commit;
