begin;

create extension if not exists pgcrypto;
create sequence if not exists public.transaction_receipt_number_seq;

create table if not exists public.transaction_receipts (
  id bigint generated by default as identity primary key,
  receipt_number text not null unique default
    ('RCT-' || to_char((now() at time zone 'Asia/Manila'),'YYYY') || '-' || lpad(nextval('public.transaction_receipt_number_seq')::text,8,'0')),
  verification_code text not null unique default encode(gen_random_bytes(16),'hex'),
  receipt_type text not null check (receipt_type in ('claim','return')),
  request_id bigint not null references public.borrow_requests(id) on delete restrict,
  return_id bigint references public.borrowing_returns(id) on delete restrict,
  created_by uuid references auth.users(id) on delete set null,
  snapshot jsonb not null,
  created_at timestamptz not null default now(),
  constraint transaction_receipt_reference check (
    (receipt_type='claim' and return_id is null) or (receipt_type='return' and return_id is not null)
  )
);

create unique index if not exists one_claim_receipt_per_request
  on public.transaction_receipts(request_id) where receipt_type='claim';
create unique index if not exists one_receipt_per_return
  on public.transaction_receipts(return_id) where return_id is not null;
create index if not exists transaction_receipts_request_idx on public.transaction_receipts(request_id,created_at);

alter table public.borrowing_asset_assignments add column if not exists return_id bigint
  references public.borrowing_returns(id) on delete restrict;
create index if not exists borrowing_asset_assignments_return_idx
  on public.borrowing_asset_assignments(return_id) where return_id is not null;

create or replace function public.prevent_receipt_mutation()
returns trigger language plpgsql as $$
begin
  raise exception 'Transaction receipts are immutable' using errcode='55000';
end $$;
drop trigger if exists transaction_receipts_immutable on public.transaction_receipts;
create trigger transaction_receipts_immutable before update or delete on public.transaction_receipts
for each row execute function public.prevent_receipt_mutation();

alter table public.transaction_receipts enable row level security;
drop policy if exists transaction_receipts_role_read on public.transaction_receipts;
create policy transaction_receipts_role_read on public.transaction_receipts for select to authenticated using (
  exists (select 1 from public.borrow_requests request where request.id=transaction_receipts.request_id
    and (request.user_id=auth.uid() or public.current_user_role() in ('professor','admin')))
);
revoke insert,update,delete on public.transaction_receipts from anon,authenticated;
grant select on public.transaction_receipts to authenticated;
revoke all on function public.prevent_receipt_mutation() from public;

-- Preserve accountability for transactions completed before this feature.
insert into public.transaction_receipts(receipt_type,request_id,created_by,snapshot,created_at)
select 'claim',request.id,request.released_by,
  jsonb_build_object('requestId',request.id,'studentName',request.student_name,'studentId',request.student_id,
    'borrowDate',request.borrow_date,'returnDate',request.return_date,'purpose',request.purpose,
    'processedBy',processor.full_name,
    'items',(select coalesce(jsonb_agg(jsonb_build_object('inventoryId',item.inventory_id,'name',inventory.item_name,'quantity',item.quantity) order by item.inventory_id),'[]'::jsonb)
      from public.borrow_request_items item join public.inventory inventory on inventory.id=item.inventory_id where item.request_id=request.id)),
  coalesce(request.released_at,request.updated_at)
from public.borrow_requests request left join public.profiles processor on processor.user_id=request.released_by
where request.status in ('Borrowed','Returned')
  and not exists(select 1 from public.transaction_receipts receipt where receipt.request_id=request.id and receipt.receipt_type='claim');

insert into public.transaction_receipts(receipt_type,request_id,return_id,created_by,snapshot,created_at)
select 'return',returned.request_id,returned.id,returned.processed_by,
  jsonb_build_object('requestId',request.id,'studentName',request.student_name,'studentId',request.student_id,
    'borrowDate',request.borrow_date,'returnDate',request.return_date,'purpose',request.purpose,
    'processedBy',processor.full_name,'remarks',returned.remarks,
    'items',(select coalesce(jsonb_agg(jsonb_build_object('inventoryId',item.inventory_id,'name',inventory.item_name,
      'goodQuantity',item.good_quantity,'damagedQuantity',item.damaged_quantity,'missingQuantity',item.missing_quantity,'conditionNote',item.condition_note) order by item.inventory_id),'[]'::jsonb)
      from public.borrowing_return_items item join public.inventory inventory on inventory.id=item.inventory_id where item.return_id=returned.id)),
  returned.created_at
from public.borrowing_returns returned join public.borrow_requests request on request.id=returned.request_id
left join public.profiles processor on processor.user_id=returned.processed_by
where not exists(select 1 from public.transaction_receipts receipt where receipt.return_id=returned.id);

commit;
