begin;

create sequence if not exists public.accountability_case_number_seq;

create table if not exists public.accountability_cases (
  id bigint generated by default as identity primary key,
  case_number text not null unique default ('AC-' || to_char((now() at time zone 'Asia/Manila'),'YYYY') || '-' || lpad(nextval('public.accountability_case_number_seq')::text,8,'0')),
  request_id bigint not null references public.borrow_requests(id) on delete restrict,
  return_id bigint references public.borrowing_returns(id) on delete restrict,
  inventory_id bigint not null references public.inventory(id) on delete restrict,
  user_id uuid references auth.users(id) on delete set null,
  incident_type text not null check (incident_type in ('damaged','missing','overdue')),
  affected_quantity integer not null check (affected_quantity > 0),
  description text not null check (char_length(btrim(description)) between 5 and 1000),
  evidence_notes text check (evidence_notes is null or char_length(evidence_notes) <= 2000),
  status text not null default 'open' check (status in ('open','under_review','resolved','waived')),
  resolution_type text check (resolution_type is null or resolution_type in ('repaired','replaced','recovered','returned','payment_recorded','waived')),
  resolution_note text check (resolution_note is null or char_length(btrim(resolution_note)) between 5 and 1000),
  amount numeric(12,2) check (amount is null or amount >= 0),
  opened_by uuid references auth.users(id) on delete set null,
  resolved_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz,
  constraint accountability_resolution_state check (
    (status in ('open','under_review') and resolution_type is null and resolved_by is null and resolved_at is null)
    or (status in ('resolved','waived') and resolution_type is not null and resolved_by is not null and resolved_at is not null)
  ),
  constraint accountability_waiver_state check ((status='waived') = (resolution_type='waived'))
);

create unique index if not exists accountability_return_item_type_unique
  on public.accountability_cases(return_id,inventory_id,incident_type) where return_id is not null;
create unique index if not exists accountability_overdue_request_item_unique
  on public.accountability_cases(request_id,inventory_id,incident_type) where incident_type='overdue';
create index if not exists accountability_user_status_idx on public.accountability_cases(user_id,status,created_at desc);
create index if not exists accountability_status_idx on public.accountability_cases(status,created_at desc);

alter table public.accountability_cases enable row level security;
drop policy if exists accountability_role_read on public.accountability_cases;
create policy accountability_role_read on public.accountability_cases for select to authenticated using (
  user_id=auth.uid() or public.current_user_role() in ('professor','admin')
);
revoke insert,update,delete on public.accountability_cases from anon,authenticated;
grant select on public.accountability_cases to authenticated;

-- Backfill existing condition-based returns without inventing financial liability.
insert into public.accountability_cases
  (request_id,return_id,inventory_id,user_id,incident_type,affected_quantity,description,evidence_notes,opened_by,created_at)
select item.request_id,item.return_id,item.inventory_id,request.user_id,kind.type,kind.quantity,
  case when char_length(btrim(coalesce(item.condition_note,''))) >= 5 then btrim(item.condition_note)
       when kind.type='damaged' then 'Damaged units recorded during return.' else 'Missing units recorded during return.' end,
  item.condition_note,returned.processed_by,item.created_at
from public.borrowing_return_items item
join public.borrowing_returns returned on returned.id=item.return_id
join public.borrow_requests request on request.id=item.request_id
cross join lateral (values ('damaged'::text,item.damaged_quantity),('missing'::text,item.missing_quantity)) kind(type,quantity)
where kind.quantity>0 and not exists (
  select 1 from public.accountability_cases existing where existing.return_id=item.return_id and existing.inventory_id=item.inventory_id and existing.incident_type=kind.type
);

insert into public.accountability_cases
  (request_id,inventory_id,user_id,incident_type,affected_quantity,description,evidence_notes,created_at)
select request.id,item.inventory_id,request.user_id,'overdue',
  greatest(item.quantity-coalesce(returned.accounted,0),1),
  'Borrowing passed its required return date with items still outstanding.',
  'Automatically created from existing overdue borrowing history.',coalesce(request.overdue_detected_at,now())
from public.borrow_requests request
join public.borrow_request_items item on item.request_id=request.id
left join (select request_id,inventory_id,sum(good_quantity+damaged_quantity+missing_quantity)::integer accounted
             from public.borrowing_return_items group by request_id,inventory_id) returned
       on returned.request_id=request.id and returned.inventory_id=item.inventory_id
where request.overdue_detected_at is not null and item.quantity>coalesce(returned.accounted,0)
on conflict (request_id,inventory_id,incident_type) where incident_type='overdue' do nothing;

do $$ begin
  alter publication supabase_realtime add table public.accountability_cases;
exception when duplicate_object then null;
end $$;

commit;
