begin;

create table if not exists public.academic_departments (
  id bigint generated by default as identity primary key,
  code text not null,
  name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (length(trim(code)) between 1 and 30),
  check (length(trim(name)) between 2 and 150)
);
create unique index if not exists academic_departments_code_unique on public.academic_departments(lower(trim(code)));
create unique index if not exists academic_departments_name_unique on public.academic_departments(lower(trim(name)));

create table if not exists public.academic_sections (
  id bigint generated by default as identity primary key,
  department_id bigint not null references public.academic_departments(id) on delete restrict,
  name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (length(trim(name)) between 1 and 100)
);
create unique index if not exists academic_sections_department_name_unique
  on public.academic_sections(department_id, lower(trim(name)));

alter table public.profiles add column if not exists department_id bigint references public.academic_departments(id) on delete restrict;
alter table public.borrow_requests add column if not exists department_id bigint references public.academic_departments(id) on delete restrict;
alter table public.borrow_requests add column if not exists section_id bigint references public.academic_sections(id) on delete restrict;
alter table public.borrow_requests add column if not exists assigned_professor_user_id uuid references public.profiles(user_id) on delete restrict;

create index if not exists profiles_professor_department_idx on public.profiles(department_id, full_name) where role='professor' and is_active=true;
create index if not exists borrow_requests_assigned_professor_idx on public.borrow_requests(assigned_professor_user_id, created_at desc);

alter table public.academic_departments enable row level security;
alter table public.academic_sections enable row level security;
revoke all on public.academic_departments, public.academic_sections from anon, authenticated;

drop policy if exists borrow_requests_role_read on public.borrow_requests;
create policy borrow_requests_role_read on public.borrow_requests for select to authenticated
  using (
    user_id=auth.uid()
    or public.current_user_role()='admin'
    or (public.current_user_role()='professor' and assigned_professor_user_id=auth.uid())
  );

drop policy if exists borrow_items_role_read on public.borrow_request_items;
create policy borrow_items_role_read on public.borrow_request_items for select to authenticated
  using (exists (
    select 1 from public.borrow_requests request
    where request.id=request_id and (
      request.user_id=auth.uid()
      or public.current_user_role()='admin'
      or (public.current_user_role()='professor' and request.assigned_professor_user_id=auth.uid())
    )
  ));

commit;
