begin;

create table if not exists public.admin_signatures (
  admin_user_id uuid primary key references public.profiles(user_id) on delete cascade,
  image_data bytea not null,
  mime_type text not null check (mime_type in ('image/png','image/jpeg')),
  image_hash text not null check (image_hash ~ '^[0-9a-f]{64}$'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.borrowing_transaction_signatures (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.borrow_requests(id) on delete restrict,
  transaction_type text not null check (transaction_type in ('release','return')),
  return_id bigint references public.borrowing_returns(id) on delete restrict,
  staff_user_id uuid not null references public.profiles(user_id) on delete restrict,
  staff_name text not null,
  signature_image bytea not null,
  signature_mime_type text not null check (signature_mime_type in ('image/png','image/jpeg')),
  signature_hash text not null check (signature_hash ~ '^[0-9a-f]{64}$'),
  signed_at timestamptz not null default now(),
  check ((transaction_type='release' and return_id is null) or (transaction_type='return' and return_id is not null))
);

create unique index if not exists borrowing_release_signature_unique
  on public.borrowing_transaction_signatures(request_id) where transaction_type='release';
create unique index if not exists borrowing_return_signature_unique
  on public.borrowing_transaction_signatures(return_id) where transaction_type='return';

create or replace function public.validate_authorization_signature_owner()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if tg_table_name='admin_signatures' and not exists (
    select 1 from public.profiles where user_id=new.admin_user_id and role='admin' and is_active=true
  ) then
    raise exception 'Administrator signatures require an active Admin account.' using errcode='23514';
  end if;
  if tg_table_name='borrowing_transaction_signatures' and not exists (
    select 1 from public.profiles where user_id=new.staff_user_id and role='staff' and is_active=true
  ) then
    raise exception 'Release and return signatures require an active Staff account.' using errcode='23514';
  end if;
  return new;
end;
$$;

drop trigger if exists admin_signature_owner_check on public.admin_signatures;
create trigger admin_signature_owner_check before insert or update of admin_user_id on public.admin_signatures
for each row execute function public.validate_authorization_signature_owner();
drop trigger if exists transaction_signature_owner_check on public.borrowing_transaction_signatures;
create trigger transaction_signature_owner_check before insert or update of staff_user_id on public.borrowing_transaction_signatures
for each row execute function public.validate_authorization_signature_owner();

create or replace function public.validate_custodian_authorization_roles()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if new.verified_by is not null and not exists (
    select 1 from public.profiles where user_id=new.verified_by and role='staff' and is_active=true
  ) then
    raise exception 'Request verification requires an active Staff account.' using errcode='23514';
  end if;
  if new.approved_by is not null and not exists (
    select 1 from public.profiles where user_id=new.approved_by and role='admin' and is_active=true
  ) then
    raise exception 'Final request approval requires an active Admin account.' using errcode='23514';
  end if;
  return new;
end;
$$;

drop trigger if exists custodian_authorization_role_check on public.borrow_request_custodian_authorizations;
create trigger custodian_authorization_role_check
before insert or update of verified_by,approved_by on public.borrow_request_custodian_authorizations
for each row execute function public.validate_custodian_authorization_roles();

alter table public.admin_signatures enable row level security;
alter table public.borrowing_transaction_signatures enable row level security;
revoke all on public.admin_signatures,public.borrowing_transaction_signatures from anon,authenticated;
revoke all on function public.validate_authorization_signature_owner() from public,anon,authenticated;
revoke all on function public.validate_custodian_authorization_roles() from public,anon,authenticated;

commit;
