begin;

create table if not exists public.borrowing_document_archives (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.borrow_requests(id) on delete restrict,
  version integer not null check (version > 0),
  document_state text not null check (document_state in ('professor_authorized','staff_verified','approved','released','partially_returned','finalized')),
  filename text not null,
  mime_type text not null default 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  content bytea not null,
  sha256 text not null check (sha256 ~ '^[0-9a-f]{64}$'),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique(request_id,version)
);

create index if not exists borrowing_document_archives_request_idx
  on public.borrowing_document_archives(request_id,version desc);

create or replace function public.prevent_borrowing_document_archive_mutation()
returns trigger language plpgsql as $$ begin
  raise exception 'Archived borrowing documents are immutable.' using errcode='55000';
end; $$;

drop trigger if exists borrowing_document_archives_immutable on public.borrowing_document_archives;
create trigger borrowing_document_archives_immutable before update or delete on public.borrowing_document_archives
for each row execute function public.prevent_borrowing_document_archive_mutation();

alter table public.borrowing_document_archives enable row level security;
revoke all on public.borrowing_document_archives from anon,authenticated;
revoke all on function public.prevent_borrowing_document_archive_mutation() from public,anon,authenticated;

commit;
