begin;

create table if not exists public.calendar_closures (
  id bigint generated by default as identity primary key,
  title text not null check (length(trim(title)) between 3 and 160),
  start_date date not null,
  end_date date not null,
  department_id bigint references public.academic_departments(id) on delete restrict,
  source_kind text not null check (source_kind in ('official_holiday', 'school_announcement')),
  source_url text,
  source_key text unique,
  is_active boolean not null default true,
  confirmed_by uuid references public.profiles(user_id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_date >= start_date),
  check (end_date <= start_date + 30)
);

create index if not exists calendar_closures_active_dates_idx
  on public.calendar_closures(start_date, end_date, department_id)
  where is_active = true;

alter table public.calendar_closures enable row level security;
revoke all on public.calendar_closures from anon, authenticated;

insert into public.calendar_closures (title, start_date, end_date, source_kind, source_url, source_key)
values
  ('New Year''s Day', '2026-01-01', '2026-01-01', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-issues-proclamation-declaring-regular-holidays-special-non-working-days-for-2026/', 'ph-2026-new-year'),
  ('Chinese New Year', '2026-02-17', '2026-02-17', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-issues-proclamation-declaring-regular-holidays-special-non-working-days-for-2026/', 'ph-2026-chinese-new-year'),
  ('Eid''l Fitr', '2026-03-20', '2026-03-20', 'official_holiday', 'https://pco.gov.ph/news_releases/proclamation-no-1189-s-2026-declaring-friday-20-march-2026-a-regular-holiday-throughout-the-country-in-observance-of-eidl-fitr-feast-of-ramadhan/', 'ph-2026-eid-fitr'),
  ('Maundy Thursday', '2026-04-02', '2026-04-02', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-issues-proclamation-declaring-regular-holidays-special-non-working-days-for-2026/', 'ph-2026-maundy-thursday'),
  ('Good Friday', '2026-04-03', '2026-04-03', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-issues-proclamation-declaring-regular-holidays-special-non-working-days-for-2026/', 'ph-2026-good-friday'),
  ('Black Saturday', '2026-04-04', '2026-04-04', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-issues-proclamation-declaring-regular-holidays-special-non-working-days-for-2026/', 'ph-2026-black-saturday'),
  ('Araw ng Kagitingan', '2026-04-09', '2026-04-09', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-issues-proclamation-declaring-regular-holidays-special-non-working-days-for-2026/', 'ph-2026-kagitingan'),
  ('Labor Day', '2026-05-01', '2026-05-01', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-issues-proclamation-declaring-regular-holidays-special-non-working-days-for-2026/', 'ph-2026-labor-day'),
  ('Eid''l Adha', '2026-05-27', '2026-05-27', 'official_holiday', 'https://pco.gov.ph/news_releases/palace-declares-may-27-as-a-regular-holiday-for-eidl-adha-observance/', 'ph-2026-eid-adha'),
  ('Independence Day', '2026-06-12', '2026-06-12', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-issues-proclamation-declaring-regular-holidays-special-non-working-days-for-2026/', 'ph-2026-independence'),
  ('Ninoy Aquino Day', '2026-08-21', '2026-08-21', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-issues-proclamation-declaring-regular-holidays-special-non-working-days-for-2026/', 'ph-2026-ninoy'),
  ('National Heroes Day', '2026-08-31', '2026-08-31', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-issues-proclamation-declaring-regular-holidays-special-non-working-days-for-2026/', 'ph-2026-heroes'),
  ('All Saints'' Day', '2026-11-01', '2026-11-01', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-issues-proclamation-declaring-regular-holidays-special-non-working-days-for-2026/', 'ph-2026-all-saints'),
  ('All Souls'' Day', '2026-11-02', '2026-11-02', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-issues-proclamation-declaring-regular-holidays-special-non-working-days-for-2026/', 'ph-2026-all-souls'),
  ('Bonifacio Day', '2026-11-30', '2026-11-30', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-issues-proclamation-declaring-regular-holidays-special-non-working-days-for-2026/', 'ph-2026-bonifacio'),
  ('Immaculate Conception', '2026-12-08', '2026-12-08', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-issues-proclamation-declaring-regular-holidays-special-non-working-days-for-2026/', 'ph-2026-immaculate'),
  ('Christmas Eve', '2026-12-24', '2026-12-24', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-issues-proclamation-declaring-regular-holidays-special-non-working-days-for-2026/', 'ph-2026-christmas-eve'),
  ('Christmas Day', '2026-12-25', '2026-12-25', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-issues-proclamation-declaring-regular-holidays-special-non-working-days-for-2026/', 'ph-2026-christmas'),
  ('Rizal Day', '2026-12-30', '2026-12-30', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-issues-proclamation-declaring-regular-holidays-special-non-working-days-for-2026/', 'ph-2026-rizal'),
  ('Last Day of the Year', '2026-12-31', '2026-12-31', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-issues-proclamation-declaring-regular-holidays-special-non-working-days-for-2026/', 'ph-2026-year-end'),
  ('New Year''s Day', '2027-01-01', '2027-01-01', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-nagdeklara-ng-mga-regular-at-special-holiday-sa-2027/', 'ph-2027-new-year'),
  ('Chinese New Year', '2027-02-06', '2027-02-06', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-nagdeklara-ng-mga-regular-at-special-holiday-sa-2027/', 'ph-2027-chinese-new-year'),
  ('Maundy Thursday', '2027-03-25', '2027-03-25', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-nagdeklara-ng-mga-regular-at-special-holiday-sa-2027/', 'ph-2027-maundy-thursday'),
  ('Good Friday', '2027-03-26', '2027-03-26', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-nagdeklara-ng-mga-regular-at-special-holiday-sa-2027/', 'ph-2027-good-friday'),
  ('Black Saturday', '2027-03-27', '2027-03-27', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-nagdeklara-ng-mga-regular-at-special-holiday-sa-2027/', 'ph-2027-black-saturday'),
  ('Araw ng Kagitingan', '2027-04-09', '2027-04-09', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-nagdeklara-ng-mga-regular-at-special-holiday-sa-2027/', 'ph-2027-kagitingan'),
  ('Labor Day', '2027-05-01', '2027-05-01', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-nagdeklara-ng-mga-regular-at-special-holiday-sa-2027/', 'ph-2027-labor-day'),
  ('Independence Day', '2027-06-12', '2027-06-12', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-nagdeklara-ng-mga-regular-at-special-holiday-sa-2027/', 'ph-2027-independence'),
  ('Ninoy Aquino Day', '2027-08-21', '2027-08-21', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-nagdeklara-ng-mga-regular-at-special-holiday-sa-2027/', 'ph-2027-ninoy'),
  ('National Heroes Day', '2027-08-30', '2027-08-30', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-nagdeklara-ng-mga-regular-at-special-holiday-sa-2027/', 'ph-2027-heroes'),
  ('All Saints'' Day', '2027-11-01', '2027-11-01', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-nagdeklara-ng-mga-regular-at-special-holiday-sa-2027/', 'ph-2027-all-saints'),
  ('All Souls'' Day', '2027-11-02', '2027-11-02', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-nagdeklara-ng-mga-regular-at-special-holiday-sa-2027/', 'ph-2027-all-souls'),
  ('Bonifacio Day', '2027-11-30', '2027-11-30', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-nagdeklara-ng-mga-regular-at-special-holiday-sa-2027/', 'ph-2027-bonifacio'),
  ('Immaculate Conception', '2027-12-08', '2027-12-08', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-nagdeklara-ng-mga-regular-at-special-holiday-sa-2027/', 'ph-2027-immaculate'),
  ('Christmas Eve', '2027-12-24', '2027-12-24', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-nagdeklara-ng-mga-regular-at-special-holiday-sa-2027/', 'ph-2027-christmas-eve'),
  ('Christmas Day', '2027-12-25', '2027-12-25', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-nagdeklara-ng-mga-regular-at-special-holiday-sa-2027/', 'ph-2027-christmas'),
  ('Rizal Day', '2027-12-30', '2027-12-30', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-nagdeklara-ng-mga-regular-at-special-holiday-sa-2027/', 'ph-2027-rizal'),
  ('Last Day of the Year', '2027-12-31', '2027-12-31', 'official_holiday', 'https://pco.gov.ph/news_releases/pbbm-nagdeklara-ng-mga-regular-at-special-holiday-sa-2027/', 'ph-2027-year-end')
on conflict (source_key) do nothing;

commit;
