begin;

create table if not exists public.announcement_reviews (
  id bigint generated by default as identity primary key,
  caption text not null check (length(trim(caption)) between 10 and 10000),
  source_url text,
  source_fingerprint text not null,
  possible_suspension boolean not null,
  suggested_start_date date,
  suggested_end_date date,
  warnings jsonb not null default '[]'::jsonb,
  status text not null default 'pending' check (status in ('pending','confirmed','dismissed')),
  submitted_by uuid references public.profiles(user_id) on delete set null,
  reviewed_by uuid references public.profiles(user_id) on delete set null,
  reviewed_at timestamptz,
  closure_id bigint unique references public.calendar_closures(id) on delete restrict,
  created_at timestamptz not null default now(),
  check ((status='pending' and reviewed_at is null and closure_id is null)
    or (status='dismissed' and reviewed_at is not null and closure_id is null)
    or (status='confirmed' and reviewed_at is not null and closure_id is not null))
);

create unique index if not exists announcement_reviews_active_fingerprint_idx
  on public.announcement_reviews(source_fingerprint) where status in ('pending','confirmed');

alter table public.announcement_reviews enable row level security;
revoke all on public.announcement_reviews from anon, authenticated;

commit;
