begin;

create table if not exists public.professor_section_assignments (
  id bigint generated by default as identity primary key,
  professor_user_id uuid not null references public.profiles(user_id) on delete cascade,
  section_id bigint not null references public.academic_sections(id) on delete restrict,
  academic_year text not null default 'Unspecified' check (length(trim(academic_year)) between 1 and 30),
  term text not null default 'Unspecified' check (length(trim(term)) between 1 and 40),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (professor_user_id, section_id, academic_year, term)
);

create index if not exists professor_section_assignment_lookup_idx
  on public.professor_section_assignments(section_id, is_active, professor_user_id);
create index if not exists professor_section_assignment_professor_idx
  on public.professor_section_assignments(professor_user_id, is_active, updated_at desc);

insert into public.professor_section_assignments
  (professor_user_id, section_id, academic_year, term, is_active)
select user_id, section_id, 'Legacy', 'Legacy', true
from public.profiles
where role='professor' and section_id is not null
on conflict do nothing;

alter table public.professor_section_assignments enable row level security;
drop policy if exists professor_assignments_read on public.professor_section_assignments;
create policy professor_assignments_read on public.professor_section_assignments for select to authenticated
  using (public.current_user_is_active() and (is_active=true or public.current_user_role()='admin'));
drop policy if exists professor_assignments_admin_insert on public.professor_section_assignments;
create policy professor_assignments_admin_insert on public.professor_section_assignments for insert to authenticated
  with check (public.current_user_role()='admin');
drop policy if exists professor_assignments_admin_update on public.professor_section_assignments;
create policy professor_assignments_admin_update on public.professor_section_assignments for update to authenticated
  using (public.current_user_role()='admin') with check (public.current_user_role()='admin');
drop policy if exists professor_assignments_admin_delete on public.professor_section_assignments;
create policy professor_assignments_admin_delete on public.professor_section_assignments for delete to authenticated
  using (public.current_user_role()='admin');

revoke all on public.professor_section_assignments from anon;
grant select,insert,update,delete on public.professor_section_assignments to authenticated;
grant usage,select on sequence public.professor_section_assignments_id_seq to authenticated;

commit;
